from langchain_core.prompts import ChatPromptTemplate
from langchain.chat_models import init_chat_model
from graph.state import MainAgentState

llm = init_chat_model("groq:openai/gpt-oss-120b")

async def response_node(state: MainAgentState):
    """Merge outputs from executed sub-agents."""
    agent_responses = state.get("agent_responses", {})
    
    if not agent_responses:
        # Fallback if no agents ran, but this shouldn't happen unless rejected
        if not state.get("is_valid", True):
            return {"final_response": state.get("guardrail_reason", "Invalid query.")}
        return {"final_response": "I couldn't process your request."}

    # If only one agent ran, return its response directly to avoid LLM overhead
    if len(agent_responses) == 1:
        agent_name = list(agent_responses.keys())[0]
        agent_out = agent_responses[agent_name]
        return {"final_response": agent_out}

    # If multiple agents ran, merge their responses using the LLM
    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are the final response formatter for a smart agriculture assistant.
Below are responses generated by specialized sub-agents based on the user's query.
Synthesize these responses into a single, cohesive, and easy-to-read response.
Make sure to keep all the important information and format it nicely in Markdown.
Do not mention the names of the sub-agents."""),
        ("human", "User Query:\n{query}\n\nSub-agent Responses:\n{responses}")
    ])
    
    responses_text = "\n\n".join(f"[{name}]\n{response}" for name, response in agent_responses.items())
    
    chain = prompt | llm
    result = await chain.ainvoke({
        "query": state["user_query"],
        "responses": responses_text
    })
    
    return {"final_response": result.content}
